### ISSUE TITLE
Not working on Anki 2.1.20beta10

### ISSUE THREAD

**Issue by AnKingMed** [Arthur-Milchior/anki-export-from-browser#7] opened 2020-02-13 18:18 UTC
When I click export selected from the menu it just brings up the default export dialog as if I had done File->export.  I can no longer export what was selected with the add-on.  I can however use the now built in function, but it is in a different menu and that will surely confuse people

**Comment by Arthur-Milchior** [comment] 2020-02-14 07:52
Damien did choose the default menu. Tell it to him. I ve no control.
It will only confuse some users of this add on. At most a few thousand people according to download numbers. Probably a few hundreds actually use it. 

This add on will be marked as incompatible with 2.1.20 so the problem is void.
I marked it as incompatible with 2.1.21 because I didnt think Damien would incorporate this feature so quickly

**Closed as completed** 2020-02-14 12:06 UTC
